SELECT * FROM db_aula_revisao.clientes;
SELECT * FROM CLIENTES WHERE sexo = 'M' and estado_civil = 'S';
SELECT * FROM CLIENTES WHERE sexo = 'F' and estado_civil = 'C';
SELECT * FROM CLIENTES WHERE data_nascimento > 19891231 and estado_civil = 'S';
SELECT * FROM CLIENTES WHERE sexo = 'M' and data_nascimento > 19891231;
SELECT * FROM CLIENTES WHERE sexo = 'F' and cidade = 'São Paulo';
SELECT * FROM CLIENTES WHERE estado_civil = 'S' or estado_civil = 'C';
SELECT * FROM CLIENTES WHERE sexo = 'M' or cidade = 'Rio de Janeiro';
SELECT * FROM CLIENTES WHERE data_nascimento >= 19891231 and data_nascimento < 19931231 or data_nascimento < 19940703;
SELECT * FROM CLIENTES WHERE estado_civil = 'S' or cidade = 'Salvador';
Select Count(id) from clientes;
select count(nome) as 'nomes_nao_Nulos' from clientes;
select count(distinct cidade) as 'cidades' from clientes;
select count(estado_civil) as 'solteiros' from clientes where estado_civil = 'S';
select count(sexo) as Homens from clientes where sexo = 'M';